// <auto-generated />
using System;
using MediLabo.Patient.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediLabo.Patient.Database.Migrations
{
    [DbContext(typeof(PatientDbContext))]
    partial class PatientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediLabo.Patient.Domain.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 Brookside St",
                            DateOfBirth = new DateOnly(1966, 12, 31),
                            FirstName = "Test",
                            Gender = "F",
                            LastName = "TestNone",
                            PhoneNumber = "100-222-3333"
                        },
                        new
                        {
                            Id = 2,
                            Address = "2 High St",
                            DateOfBirth = new DateOnly(1945, 6, 24),
                            FirstName = "Test",
                            Gender = "M",
                            LastName = "TestBorderline",
                            PhoneNumber = "200-333-4444"
                        },
                        new
                        {
                            Id = 3,
                            Address = "3 Club Road",
                            DateOfBirth = new DateOnly(2004, 6, 18),
                            FirstName = "Test",
                            Gender = "M",
                            LastName = "TestInDanger",
                            PhoneNumber = "300-444-5555"
                        },
                        new
                        {
                            Id = 4,
                            Address = "4 Valley Dr",
                            DateOfBirth = new DateOnly(2002, 6, 28),
                            FirstName = "Test",
                            Gender = "F",
                            LastName = "TestEarlyOnset",
                            PhoneNumber = "400-555-6666"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
